// Shared memory subsystem (PLAN.md Phase 3): durable user-fact extraction and
// per-session summaries, both generated by the loaded model itself rather
// than stored as raw chat transcripts. Plain .txt files, human-readable and
// user-editable/deletable from the filesystem. Built on top of
// core/inference/ — this is the only place that decides *when* and *what*
// to prompt for; core/inference just runs prompts.
#ifndef POCKETCHAT_MEMORY_H
#define POCKETCHAT_MEMORY_H

#include <stddef.h>
#include <stdint.h>

#include "pocketchat_inference.h"

#ifdef __cplusplus
extern "C" {
#endif

// Reads memory_dir/profile.txt (if present) and up to `max_summaries` of the
// most recent files under memory_dir/summaries/, formatted into a single
// string meant to be spliced into a system prompt. Bounded to roughly
// `max_chars` — if the content doesn't fit, the oldest part is dropped first.
// Returns an empty (non-null) string if there's no memory yet, or NULL on
// allocation failure. Caller must free the result with pc_memory_free_string().
char * pc_memory_build_context(const char * memory_dir, int max_summaries, size_t max_chars);
void pc_memory_free_string(char * s);

// Prompts `model` (via a fresh, isolated context of its own — the caller's
// live chat context/KV cache is never touched) to:
//   1. extract/merge durable facts from `messages` into memory_dir/profile.txt
//   2. append a short summary of the session to
//      memory_dir/summaries/<timestamp>.txt
// Intended to run after a session ends (or every N turns) — see PLAN.md
// Phase 3. `messages` should be the session's transcript (or however much of
// it the caller wants summarized/extracted from).
// Returns 0 on success, negative on error (see pc_memory_last_error()).
int pc_memory_update_session(
    pc_model               * model,
    const char              * memory_dir,
    const pc_chat_message   * messages,
    size_t                    n_messages,
    uint32_t                  n_ctx,
    int32_t                   n_threads
);

// Human-readable message for the last error on this thread; empty string if none.
const char * pc_memory_last_error(void);

#ifdef __cplusplus
}
#endif

#endif // POCKETCHAT_MEMORY_H
