// Shared memory subsystem (PLAN.md Phase 3): durable user-fact extraction and
// per-session summaries, both generated by the loaded model itself rather
// than stored as raw chat transcripts. Plain .txt files, human-readable and
// user-editable/deletable from the filesystem. Built on top of
// core/inference/ — this is the only place that decides *when* and *what*
// to prompt for; core/inference just runs prompts.
#ifndef POCKETCHAT_MEMORY_H
#define POCKETCHAT_MEMORY_H

#include <stddef.h>
#include <stdint.h>

#include "pocketchat_inference.h"

#ifdef __cplusplus
extern "C" {
#endif

// Reads memory_dir/profile.txt (always included in full when present) and up
// to `max_summaries` entries from memory_dir/summaries/, formatted into a
// single string meant to be spliced into a system prompt.
//
// `query` — typically the current conversation's latest message/topic — picks
// which summaries are most relevant via an in-memory SQLite FTS5/BM25 index
// built fresh from the summary files on every call (FR-013; see the
// relevant_summary_files() doc comment in the .cpp for why it's never
// persisted to disk). Pass NULL or "" to always use plain recency instead
// (e.g. there's no conversation yet to key off of). Also falls back to
// recency automatically whenever FTS5 isn't available on this build/device,
// `query` has no usable search terms once sanitized, or it simply matches
// nothing — any of those count as "no strong match."
//
// Bounded to roughly `max_chars` — if the content doesn't fit, the oldest
// part is dropped first. Returns an empty (non-null) string if there's no
// memory yet, or NULL on allocation failure. Caller must free the result with
// pc_memory_free_string().
char * pc_memory_build_context(const char * memory_dir, const char * query, int max_summaries, size_t max_chars);
void pc_memory_free_string(char * s);

// FR-026: one summary matched by pc_memory_search(). `timestamp` is the
// summary's base filename (e.g. "20260101-090000", no extension) — pass it
// back to pc_memory_delete_summary() to delete this entry. `annotation` is
// "" when the summary has none (FR-023).
typedef struct {
    char * timestamp;
    char * content;
    char * annotation;
} pc_memory_search_result;

// FR-026: direct user-facing search across memory_dir/summaries/, ranked by
// the same FTS5/BM25 relevance pc_memory_build_context uses (including
// FR-023's annotation weighting) — but unlike that function, this does NOT
// fall back to recency when there's no strong match. A search box with zero
// results should say so, not silently show unrelated recent entries.
// On success (0), *out_results/*out_count describe up to `max_results`
// matches (best first); *out_count may legitimately be 0. Free with
// pc_memory_free_search_results(). Returns negative on error (invalid
// arguments or allocation failure) — see pc_memory_last_error().
int pc_memory_search(
    const char * memory_dir, const char * query, int max_results,
    pc_memory_search_result ** out_results, size_t * out_count);

void pc_memory_free_search_results(pc_memory_search_result * results, size_t count);

// FR-033: permanently deletes memory_dir/summaries/<timestamp>.txt and its
// .annotation.txt sibling if present (an annotation can't outlive the
// summary it's attached to). Deleting an already-gone entry is not an
// error. Returns 0 on success, negative on invalid arguments.
int pc_memory_delete_summary(const char * memory_dir, const char * timestamp);

// FR-033: deletes exactly the first line of memory_dir/profile.txt whose
// trimmed text exactly matches trimmed `fact_text` (profile.txt is one
// durable fact per line — see pc_memory_update_session's extraction prompt).
// A caller should re-read profile.txt after this rather than deleting by
// remembered line position, since positions shift once a line is removed.
// Not finding a match is not an error. Returns 0 on success, negative on
// invalid arguments.
int pc_memory_delete_profile_fact(const char * memory_dir, const char * fact_text);

typedef enum {
    PC_MEMORY_PHASE_EXTRACTING_FACTS = 0,
    PC_MEMORY_PHASE_SUMMARIZING = 1,
} pc_memory_phase;

// Called once per generated piece of text during pc_memory_update_session,
// tagged with which of its two generation passes produced it — lets a caller
// show live progress instead of a single opaque "updating memory" spinner.
// Return 0 to stop that phase's generation early (the update as a whole
// still completes normally), non-zero to keep going.
typedef int (*pc_memory_progress_callback)(pc_memory_phase phase, const char * piece, void * user_data);

// Prompts `model` (via a fresh, isolated context of its own — the caller's
// live chat context/KV cache is never touched) to:
//   1. extract/merge durable facts from `messages` into memory_dir/profile.txt
//   2. append a short summary of the session to
//      memory_dir/summaries/<timestamp>.txt
// Intended to run after a session ends (or every N turns) — see PLAN.md
// Phase 3. `messages` should be the session's transcript (or however much of
// it the caller wants summarized/extracted from). `progress_callback` may be
// NULL if the caller doesn't want streaming updates.
// Returns 0 on success, negative on error (see pc_memory_last_error()).
int pc_memory_update_session(
    pc_model                     * model,
    const char                    * memory_dir,
    const pc_chat_message         * messages,
    size_t                          n_messages,
    uint32_t                        n_ctx,
    int32_t                         n_threads,
    pc_memory_progress_callback     progress_callback,
    void                           * progress_user_data
);

// Human-readable message for the last error on this thread; empty string if none.
const char * pc_memory_last_error(void);

#ifdef __cplusplus
}
#endif

#endif // POCKETCHAT_MEMORY_H
